apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: rancher.io/local-path
  creationTimestamp: "2022-03-18T11:20:09Z"
  finalizers:
  - kubernetes.io/pv-protection
  name: pvc-1611eb50-866a-44c8-9106-22a8011617f2
  resourceVersion: "31392"
  uid: f49ceadc-f2a1-4bb3-b9fc-38c0e71bc060
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: data-pzoo-2
    namespace: kafka
    resourceVersion: "31271"
    uid: 1611eb50-866a-44c8-9106-22a8011617f2
  hostPath:
    path: /var/local-path-provisioner/pvc-1611eb50-866a-44c8-9106-22a8011617f2_kafka_data-pzoo-2
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kind-control-plane
  persistentVolumeReclaimPolicy: Delete
  storageClassName: standard
  volumeMode: Filesystem
status:
  phase: Bound
