apiVersion: v1
kind: Service
metadata:
  name: kafkacat
  labels:
    app: kafkacat
spec:
  ports:
  - protocol: TCP
    targetPort: 22  
    port: 32222
    nodePort: 32222
    name: kafkacat
  selector:
    app: kafka-cat
  type: NodePort

