---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: kafka-cat
  namespace: kafka
spec:
  serviceName: "kafkacat-service"
  replicas: 1
  selector:
    matchLabels:
      app: kafka-cat
  template:
    metadata:
      labels:
        app: kafka-cat
    spec:
      containers:
        - name: kafka-cat
          image: confluentinc/cp-kafkacat
          command: ["/bin/bash"]
          args: ["-c", "trap : TERM INT; sleep infinity & wait"]
